# Othentic CLI, make sure to have correct access key in Dockerfile
x-othentic-cli: &othentic-cli
  env_file:
    - .env
  build:
    context: .
    dockerfile: ./Dockerfile

# Services
services:
  aggregator:
    <<: *othentic-cli
    command: [
      "node", 
      "aggregator", 
      "--json-rpc",
      "--gas-multiplier",
      "1.25"
      # "--announce",
      # "/dns4/aggregator.avs.skatechain.org/tcp/6666",
    ]
    ports:
      - "8545:8545"
      - "9876:9876"
